reconnect:
  name: "Reconnect AirTouch2"
  description: "Force reconnect to AirTouch2 system"
  fields:
    device_id:
      name: "Device ID"
      description: "Device ID of the AirTouch2 system (optional)"
      required: false
      example: "abc123"
      selector:
        text: